# Generated by Django 4.1.1 on 2022-09-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='products',
        ),
        migrations.AddField(
            model_name='quotation',
            name='products',
            field=models.ManyToManyField(to='api.productonquotation'),
        ),
    ]
