# Generated by Django 4.1 on 2022-11-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_quotation_products_quotation_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.CharField(default='', max_length=200),
        ),
    ]
