# Generated by Django 4.1 on 2022-11-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_quotation_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='identification',
            field=models.CharField(default='', max_length=50),
        ),
    ]
